// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-m0qP6cezndKeykAT3IrUft5rKj14xb0',
    appId: '1:18679242060:web:70a3216e0740c60a8a83e9',
    messagingSenderId: '18679242060',
    projectId: 'findwork-94920',
    authDomain: 'findwork-94920.firebaseapp.com',
    storageBucket: 'findwork-94920.appspot.com',
    measurementId: 'G-0TXYK78FE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD8U3sGAZ2fpvZn8qrei9rivJ20J_sTKQ',
    appId: '1:18679242060:android:81318b827abaa4978a83e9',
    messagingSenderId: '18679242060',
    projectId: 'findwork-94920',
    storageBucket: 'findwork-94920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_MfSzAjDi-xpv5FOFG1soI0UB25akLjM',
    appId: '1:18679242060:ios:958c1234c8e8e56a8a83e9',
    messagingSenderId: '18679242060',
    projectId: 'findwork-94920',
    storageBucket: 'findwork-94920.appspot.com',
    iosBundleId: 'com.example.learningEnglishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-m0qP6cezndKeykAT3IrUft5rKj14xb0',
    appId: '1:18679242060:web:7fe904c6277042de8a83e9',
    messagingSenderId: '18679242060',
    projectId: 'findwork-94920',
    authDomain: 'findwork-94920.firebaseapp.com',
    storageBucket: 'findwork-94920.appspot.com',
    measurementId: 'G-ZZ428PTCWV',
  );
}
